[workspace]
members = ["sdr", "fm-receiver", "fm-single", "am-receiver", "am-single", "chu-decoder", "freq-scanner", "iq-print", "adsb-decoder", "adsb-api", "flight-tracker", "wave-demo", "iq-demo"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
num-complex = "0.4"
